import { CareerCluster } from "./types";

export const CAREER_CLUSTERS: CareerCluster[] = [
  // ══════════════════════════════════════════
  // 1. Technology & Digital Innovation
  // ══════════════════════════════════════════
  {
    id: "tech",
    name: "Technology & Digital Innovation",
    emoji: "\u{1F4BB}",
    color: "#4A90D9",
    description: "Build the apps, websites, games, and AI systems that shape how we live.",
    pathways: [
      {
        id: "tech-software",
        name: "Software & App Development",
        careers: [
          {
            id: "tech-software-dev",
            title: "Software Developer",
            hook: "Write the code that powers the apps and games millions of people use every day.",
            emoji: "\u{1F468}\u200D\u{1F4BB}",
            salaryRange: { entry: 75000, experienced: 168000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "tech-mobile-dev",
            title: "Mobile App Developer",
            hook: "Create the next hit app that lives on everyone's phone.",
            emoji: "\u{1F4F1}",
            salaryRange: { entry: 70000, experienced: 160000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "tech-web-dev",
            title: "Web Developer",
            hook: "Design and build the websites and online experiences people visit every day.",
            emoji: "\u{1F310}",
            salaryRange: { entry: 50000, experienced: 120000 },
            growth: "moderate",
            education: "Associate's or Bachelor's degree",
          },
          {
            id: "tech-game-dev",
            title: "Video Game Developer",
            hook: "Turn your wildest game ideas into playable worlds that people love.",
            emoji: "\u{1F3AE}",
            salaryRange: { entry: 55000, experienced: 140000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "tech-data",
        name: "Data & Artificial Intelligence",
        careers: [
          {
            id: "tech-data-scientist",
            title: "Data Scientist",
            hook: "Find hidden patterns in massive amounts of data to help companies make smarter decisions.",
            emoji: "\u{1F4CA}",
            salaryRange: { entry: 70000, experienced: 160000 },
            growth: "high",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "tech-ai-engineer",
            title: "AI / Machine Learning Engineer",
            hook: "Teach computers to think, learn, and solve problems like humans do \u2014 sometimes even better.",
            emoji: "\u{1F916}",
            salaryRange: { entry: 90000, experienced: 180000 },
            growth: "high",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "tech-database-admin",
            title: "Database Administrator",
            hook: "Organize and protect the enormous libraries of digital information that businesses rely on.",
            emoji: "\u{1F5C4}\uFE0F",
            salaryRange: { entry: 55000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "tech-cyber",
        name: "Cybersecurity",
        careers: [
          {
            id: "tech-security-analyst",
            title: "Cybersecurity Analyst",
            hook: "Protect computers and networks from hackers like a digital detective and guardian.",
            emoji: "\u{1F6E1}\uFE0F",
            salaryRange: { entry: 65000, experienced: 165000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "tech-pen-tester",
            title: "Penetration Tester",
            hook: "Get paid to hack into systems and find their weak spots before the bad guys do.",
            emoji: "\u{1F513}",
            salaryRange: { entry: 60000, experienced: 150000 },
            growth: "high",
            education: "Bachelor's degree + certifications",
          },
          {
            id: "tech-forensics",
            title: "Digital Forensics Investigator",
            hook: "Solve cybercrimes by uncovering digital clues hidden in computers and phones.",
            emoji: "\u{1F50D}",
            salaryRange: { entry: 55000, experienced: 125000 },
            growth: "high",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "tech-it",
        name: "IT Support & Networking",
        careers: [
          {
            id: "tech-it-support",
            title: "IT Support Specialist",
            hook: "Be the tech hero who fixes computer problems and keeps everything running smoothly.",
            emoji: "\u{1F527}",
            salaryRange: { entry: 38000, experienced: 80000 },
            growth: "moderate",
            education: "Associate's degree or certifications",
          },
          {
            id: "tech-network-admin",
            title: "Network Administrator",
            hook: "Build and manage the invisible highways that connect computers around the world.",
            emoji: "\u{1F50C}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "tech-cloud-architect",
            title: "Cloud Computing Architect",
            hook: "Design the powerful cloud systems that let people store and access data from anywhere.",
            emoji: "\u2601\uFE0F",
            salaryRange: { entry: 80000, experienced: 170000 },
            growth: "high",
            education: "Bachelor's degree + experience",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 2. Health & Medical Sciences
  // ══════════════════════════════════════════
  {
    id: "health",
    name: "Health & Medical Sciences",
    emoji: "\u{1F3E5}",
    color: "#E74C3C",
    description: "Save lives, cure diseases, and help people live healthier, happier lives.",
    pathways: [
      {
        id: "health-clinical",
        name: "Doctors & Clinical Care",
        careers: [
          {
            id: "health-physician",
            title: "Physician / Doctor",
            hook: "Diagnose mysteries inside the human body and heal people using science and skill.",
            emoji: "\u{1F468}\u200D\u2695\uFE0F",
            salaryRange: { entry: 150000, experienced: 300000 },
            growth: "stable",
            education: "Doctoral degree (MD/DO)",
          },
          {
            id: "health-surgeon",
            title: "Surgeon",
            hook: "Perform incredible operations that literally fix what's broken inside people's bodies.",
            emoji: "\u{1F52C}",
            salaryRange: { entry: 200000, experienced: 400000 },
            growth: "stable",
            education: "Doctoral degree (MD/DO) + residency",
          },
          {
            id: "health-nurse-practitioner",
            title: "Nurse Practitioner",
            hook: "Provide hands-on healthcare and even prescribe medicine to patients who need you.",
            emoji: "\u{1F489}",
            salaryRange: { entry: 95000, experienced: 155000 },
            growth: "high",
            education: "Master's degree",
          },
          {
            id: "health-pa",
            title: "Physician Assistant",
            hook: "Team up with doctors to examine patients, order tests, and help people get better fast.",
            emoji: "\u{1FA7A}",
            salaryRange: { entry: 90000, experienced: 155000 },
            growth: "high",
            education: "Master's degree",
          },
        ],
      },
      {
        id: "health-nursing",
        name: "Nursing & Patient Care",
        careers: [
          {
            id: "health-rn",
            title: "Registered Nurse",
            hook: "Be the caring expert who's with patients through their toughest moments and biggest recoveries.",
            emoji: "\u{1F469}\u200D\u2695\uFE0F",
            salaryRange: { entry: 66000, experienced: 135000 },
            growth: "moderate",
            education: "Bachelor's degree (BSN)",
          },
          {
            id: "health-emt",
            title: "EMT / Paramedic",
            hook: "Race to emergencies in an ambulance and save lives when every second counts.",
            emoji: "\u{1F691}",
            salaryRange: { entry: 35000, experienced: 65000 },
            growth: "moderate",
            education: "Postsecondary certificate",
          },
          {
            id: "health-surgical-tech",
            title: "Surgical Technologist",
            hook: "Work right alongside surgeons in the operating room, handing them the tools to save lives.",
            emoji: "\u{1F3E5}",
            salaryRange: { entry: 40000, experienced: 72000 },
            growth: "moderate",
            education: "Postsecondary certificate or Associate's",
          },
        ],
      },
      {
        id: "health-dental-vision",
        name: "Dental, Vision & Specialty Care",
        careers: [
          {
            id: "health-dentist",
            title: "Dentist",
            hook: "Keep people smiling with healthy teeth using cool tools and the latest dental science.",
            emoji: "\u{1F9B7}",
            salaryRange: { entry: 100000, experienced: 200000 },
            growth: "moderate",
            education: "Doctoral degree (DDS/DMD)",
          },
          {
            id: "health-dental-hygienist",
            title: "Dental Hygienist",
            hook: "Clean teeth, take X-rays, and teach patients how to keep their smiles bright.",
            emoji: "\u2728",
            salaryRange: { entry: 65000, experienced: 110000 },
            growth: "moderate",
            education: "Associate's degree",
          },
          {
            id: "health-optometrist",
            title: "Optometrist",
            hook: "Help people see the world clearly by testing their eyes and prescribing the perfect glasses.",
            emoji: "\u{1F453}",
            salaryRange: { entry: 80000, experienced: 160000 },
            growth: "moderate",
            education: "Doctoral degree (OD)",
          },
          {
            id: "health-pharmacist",
            title: "Pharmacist",
            hook: "Be a medicine expert who makes sure people get exactly the right drugs to feel better.",
            emoji: "\u{1F48A}",
            salaryRange: { entry: 100000, experienced: 160000 },
            growth: "stable",
            education: "Doctoral degree (PharmD)",
          },
        ],
      },
      {
        id: "health-therapy",
        name: "Therapy & Rehabilitation",
        careers: [
          {
            id: "health-physical-therapist",
            title: "Physical Therapist",
            hook: "Help injured athletes and patients rebuild their strength and get back to doing what they love.",
            emoji: "\u{1F3CB}\uFE0F",
            salaryRange: { entry: 70000, experienced: 120000 },
            growth: "moderate",
            education: "Doctoral degree (DPT)",
          },
          {
            id: "health-occupational-therapist",
            title: "Occupational Therapist",
            hook: "Help people relearn everyday skills like eating, writing, and getting dressed after injuries.",
            emoji: "\u{1F932}",
            salaryRange: { entry: 65000, experienced: 110000 },
            growth: "moderate",
            education: "Master's degree",
          },
          {
            id: "health-speech-pathologist",
            title: "Speech-Language Pathologist",
            hook: "Help kids and adults find their voice by treating speech and communication challenges.",
            emoji: "\u{1F5E3}\uFE0F",
            salaryRange: { entry: 60000, experienced: 110000 },
            growth: "moderate",
            education: "Master's degree",
          },
        ],
      },
      {
        id: "health-research",
        name: "Medical Research & Public Health",
        careers: [
          {
            id: "health-biomedical-researcher",
            title: "Biomedical Research Scientist",
            hook: "Discover new cures and treatments in a lab that could save millions of lives.",
            emoji: "\u{1F9EC}",
            salaryRange: { entry: 55000, experienced: 120000 },
            growth: "moderate",
            education: "Doctoral degree (PhD)",
          },
          {
            id: "health-epidemiologist",
            title: "Epidemiologist",
            hook: "Track down the causes of diseases and outbreaks like a medical detective protecting communities.",
            emoji: "\u{1F9A0}",
            salaryRange: { entry: 55000, experienced: 115000 },
            growth: "moderate",
            education: "Master's degree",
          },
          {
            id: "health-public-health",
            title: "Public Health Specialist",
            hook: "Create programs that keep entire communities healthy, from clean water to vaccination drives.",
            emoji: "\u{1F30D}",
            salaryRange: { entry: 45000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 3. Engineering & Applied Science
  // ══════════════════════════════════════════
  {
    id: "engineering",
    name: "Engineering & Applied Science",
    emoji: "\u2699\uFE0F",
    color: "#F39C12",
    description: "Design, build, and improve the structures, machines, and systems that shape our world.",
    pathways: [
      {
        id: "eng-mechanical",
        name: "Mechanical & Aerospace Engineering",
        careers: [
          {
            id: "eng-mechanical-engineer",
            title: "Mechanical Engineer",
            hook: "Design everything from tiny watch parts to giant jet engines that push the limits of physics.",
            emoji: "\u2699\uFE0F",
            salaryRange: { entry: 70000, experienced: 135000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "eng-aerospace-engineer",
            title: "Aerospace Engineer",
            hook: "Design rockets, satellites, and aircraft that fly through the sky and into outer space.",
            emoji: "\u{1F680}",
            salaryRange: { entry: 85000, experienced: 170000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-robotics-engineer",
            title: "Robotics Engineer",
            hook: "Build robots that can do amazing things, from exploring Mars to performing surgery.",
            emoji: "\u{1F9BE}",
            salaryRange: { entry: 75000, experienced: 150000 },
            growth: "high",
            education: "Bachelor's or Master's degree",
          },
        ],
      },
      {
        id: "eng-electrical",
        name: "Electrical & Computer Engineering",
        careers: [
          {
            id: "eng-electrical-engineer",
            title: "Electrical Engineer",
            hook: "Design the circuits and electrical systems that power everything from phones to power grids.",
            emoji: "\u26A1",
            salaryRange: { entry: 70000, experienced: 150000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-computer-hardware",
            title: "Computer Hardware Engineer",
            hook: "Design the physical chips and circuit boards that are the brains inside every device.",
            emoji: "\u{1F5A5}\uFE0F",
            salaryRange: { entry: 80000, experienced: 170000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-drone-engineer",
            title: "Drone / UAV Engineer",
            hook: "Design and program drones that deliver packages, film movies, and even save lives.",
            emoji: "\u{1F6F8}",
            salaryRange: { entry: 65000, experienced: 130000 },
            growth: "high",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "eng-civil",
        name: "Civil & Environmental Engineering",
        careers: [
          {
            id: "eng-civil-engineer",
            title: "Civil Engineer",
            hook: "Design bridges, highways, and skyscrapers that millions of people use every single day.",
            emoji: "\u{1F309}",
            salaryRange: { entry: 66000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-environmental-engineer",
            title: "Environmental Engineer",
            hook: "Use science and engineering to clean up pollution and protect our planet for the future.",
            emoji: "\u{1F33F}",
            salaryRange: { entry: 60000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-surveyor",
            title: "Surveyor",
            hook: "Use GPS, lasers, and math to map out exactly where buildings, roads, and boundaries should go.",
            emoji: "\u{1F4D0}",
            salaryRange: { entry: 45000, experienced: 90000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "eng-biomedical",
        name: "Biomedical & Chemical Engineering",
        careers: [
          {
            id: "eng-biomedical-engineer",
            title: "Biomedical Engineer",
            hook: "Invent the medical devices and artificial organs that give people second chances at life.",
            emoji: "\u{1FAC0}",
            salaryRange: { entry: 65000, experienced: 140000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-chemical-engineer",
            title: "Chemical Engineer",
            hook: "Create new materials, fuels, and medicines by combining chemistry with engineering.",
            emoji: "\u{1F9EA}",
            salaryRange: { entry: 70000, experienced: 140000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "eng-materials-scientist",
            title: "Materials Scientist",
            hook: "Invent super-strong, ultra-light, or self-healing materials that seem like science fiction.",
            emoji: "\u{1F529}",
            salaryRange: { entry: 60000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 4. Science, Math & Research
  // ══════════════════════════════════════════
  {
    id: "science",
    name: "Science, Math & Research",
    emoji: "\u{1F52C}",
    color: "#9B59B6",
    description: "Explore the mysteries of the universe, from tiny atoms to distant galaxies.",
    pathways: [
      {
        id: "science-life",
        name: "Life Sciences & Biology",
        careers: [
          {
            id: "science-biologist",
            title: "Biologist",
            hook: "Study everything from microscopic cells to entire ecosystems to unlock the secrets of life.",
            emoji: "\u{1F9EB}",
            salaryRange: { entry: 48000, experienced: 100000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "science-marine-biologist",
            title: "Marine Biologist",
            hook: "Dive into the ocean to study sharks, coral reefs, and the amazing creatures of the deep.",
            emoji: "\u{1F40B}",
            salaryRange: { entry: 45000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "science-geneticist",
            title: "Geneticist",
            hook: "Decode the DNA blueprints that make every living thing unique \u2014 and find cures for genetic diseases.",
            emoji: "\u{1F9EC}",
            salaryRange: { entry: 55000, experienced: 115000 },
            growth: "moderate",
            education: "Doctoral degree",
          },
          {
            id: "science-zoologist",
            title: "Zoologist / Wildlife Biologist",
            hook: "Study wild animals in their natural habitats and help protect endangered species.",
            emoji: "\u{1F981}",
            salaryRange: { entry: 45000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
        ],
      },
      {
        id: "science-physical",
        name: "Physical Sciences",
        careers: [
          {
            id: "science-physicist",
            title: "Physicist",
            hook: "Discover the fundamental laws that govern everything in the universe, from atoms to black holes.",
            emoji: "\u269B\uFE0F",
            salaryRange: { entry: 65000, experienced: 155000 },
            growth: "moderate",
            education: "Doctoral degree",
          },
          {
            id: "science-chemist",
            title: "Chemist",
            hook: "Mix and test chemicals to create new medicines, materials, and solutions to real problems.",
            emoji: "\u{1F9EA}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "science-astronomer",
            title: "Astronomer",
            hook: "Use powerful telescopes to explore distant galaxies, stars, and planets beyond our solar system.",
            emoji: "\u{1F52D}",
            salaryRange: { entry: 65000, experienced: 155000 },
            growth: "moderate",
            education: "Doctoral degree",
          },
        ],
      },
      {
        id: "science-earth",
        name: "Earth & Environmental Science",
        careers: [
          {
            id: "science-geologist",
            title: "Geologist",
            hook: "Read the story of Earth written in its rocks, volcanoes, and earthquakes over billions of years.",
            emoji: "\u{1F30B}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "science-meteorologist",
            title: "Meteorologist",
            hook: "Predict storms, tornadoes, and weather patterns that affect millions of people's daily lives.",
            emoji: "\u{1F32A}\uFE0F",
            salaryRange: { entry: 50000, experienced: 105000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "science-environmental-scientist",
            title: "Environmental Scientist",
            hook: "Investigate pollution, climate change, and habitat loss to protect our planet's future.",
            emoji: "\u{1F30E}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "science-climate-scientist",
            title: "Climate Scientist",
            hook: "Study how Earth's climate is changing and figure out what we can do to slow it down.",
            emoji: "\u{1F321}\uFE0F",
            salaryRange: { entry: 55000, experienced: 115000 },
            growth: "moderate",
            education: "Master's or Doctoral degree",
          },
        ],
      },
      {
        id: "science-math",
        name: "Mathematics & Statistics",
        careers: [
          {
            id: "science-mathematician",
            title: "Mathematician",
            hook: "Solve puzzles that nobody else can crack using the pure power of numbers and logic.",
            emoji: "\u{1F522}",
            salaryRange: { entry: 60000, experienced: 135000 },
            growth: "stable",
            education: "Master's or Doctoral degree",
          },
          {
            id: "science-statistician",
            title: "Statistician",
            hook: "Turn messy data into clear answers that help doctors, businesses, and governments make better choices.",
            emoji: "\u{1F4C8}",
            salaryRange: { entry: 60000, experienced: 130000 },
            growth: "high",
            education: "Master's degree",
          },
          {
            id: "science-actuary",
            title: "Actuary",
            hook: "Use math to predict the future and help companies understand risk \u2014 one of the top-paying jobs there is.",
            emoji: "\u{1F4C9}",
            salaryRange: { entry: 70000, experienced: 155000 },
            growth: "high",
            education: "Bachelor's degree + exams",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 5. Creative Arts, Design & Media
  // ══════════════════════════════════════════
  {
    id: "creative",
    name: "Creative Arts, Design & Media",
    emoji: "\u{1F3A8}",
    color: "#E91E63",
    description: "Express yourself and tell stories through art, music, film, writing, and design.",
    pathways: [
      {
        id: "creative-visual",
        name: "Visual Arts & Design",
        careers: [
          {
            id: "creative-graphic-designer",
            title: "Graphic Designer",
            hook: "Create the logos, posters, and visuals that make brands and products look amazing.",
            emoji: "\u{1F3A8}",
            salaryRange: { entry: 38000, experienced: 90000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "creative-ux-designer",
            title: "UX/UI Designer",
            hook: "Design the look and feel of apps and websites so they're beautiful and easy to use.",
            emoji: "\u{1F4F2}",
            salaryRange: { entry: 55000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "creative-animator",
            title: "Animator / Motion Designer",
            hook: "Bring characters and stories to life frame by frame, from cartoons to blockbuster movies.",
            emoji: "\u{1F3AC}",
            salaryRange: { entry: 50000, experienced: 130000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "creative-fine-artist",
            title: "Fine Artist / Illustrator",
            hook: "Create original paintings, sculptures, and illustrations that move people and hang in galleries.",
            emoji: "\u{1F58C}\uFE0F",
            salaryRange: { entry: 30000, experienced: 80000 },
            growth: "stable",
            education: "Bachelor's degree or self-taught",
          },
        ],
      },
      {
        id: "creative-film",
        name: "Film, Video & Photography",
        careers: [
          {
            id: "creative-film-director",
            title: "Film / Video Director",
            hook: "Call the shots on a movie set and turn a script into an unforgettable visual experience.",
            emoji: "\u{1F3A5}",
            salaryRange: { entry: 40000, experienced: 130000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "creative-video-editor",
            title: "Video Editor",
            hook: "Cut, arrange, and polish raw footage into the polished videos and movies people watch.",
            emoji: "\u2702\uFE0F",
            salaryRange: { entry: 40000, experienced: 100000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "creative-photographer",
            title: "Photographer",
            hook: "Capture once-in-a-lifetime moments and stunning images that tell powerful stories.",
            emoji: "\u{1F4F8}",
            salaryRange: { entry: 30000, experienced: 80000 },
            growth: "stable",
            education: "No formal requirement",
          },
          {
            id: "creative-content-creator",
            title: "Content Creator / YouTuber",
            hook: "Build your own audience by making videos, posts, and content that people can't stop watching.",
            emoji: "\u{1F4F9}",
            salaryRange: { entry: 25000, experienced: 100000 },
            growth: "high",
            education: "No formal requirement",
          },
        ],
      },
      {
        id: "creative-music",
        name: "Music & Performing Arts",
        careers: [
          {
            id: "creative-musician",
            title: "Musician / Singer",
            hook: "Perform live, record albums, and share your music with fans around the world.",
            emoji: "\u{1F3B5}",
            salaryRange: { entry: 25000, experienced: 90000 },
            growth: "stable",
            education: "No formal requirement",
          },
          {
            id: "creative-music-producer",
            title: "Music / Audio Producer",
            hook: "Mix beats, layer sounds, and produce the tracks that get stuck in everyone's head.",
            emoji: "\u{1F3A7}",
            salaryRange: { entry: 30000, experienced: 100000 },
            growth: "stable",
            education: "No formal requirement",
          },
          {
            id: "creative-sound-engineer",
            title: "Sound Engineer",
            hook: "Control the sound at concerts, studios, and movie sets to make everything sound perfect.",
            emoji: "\u{1F50A}",
            salaryRange: { entry: 30000, experienced: 90000 },
            growth: "stable",
            education: "Associate's or Bachelor's degree",
          },
          {
            id: "creative-actor",
            title: "Actor",
            hook: "Step into someone else's shoes and bring characters to life on stage, TV, or the big screen.",
            emoji: "\u{1F3AD}",
            salaryRange: { entry: 25000, experienced: 100000 },
            growth: "stable",
            education: "No formal requirement",
          },
        ],
      },
      {
        id: "creative-writing",
        name: "Writing & Publishing",
        careers: [
          {
            id: "creative-author",
            title: "Author / Novelist",
            hook: "Create entire worlds and characters from your imagination that readers fall in love with.",
            emoji: "\u{1F4D6}",
            salaryRange: { entry: 35000, experienced: 100000 },
            growth: "stable",
            education: "No formal requirement",
          },
          {
            id: "creative-screenwriter",
            title: "Screenwriter",
            hook: "Write the scripts and dialogue for the movies and TV shows that everyone talks about.",
            emoji: "\u{1F4DD}",
            salaryRange: { entry: 35000, experienced: 120000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "creative-editor",
            title: "Editor",
            hook: "Shape and polish other writers' work to make books, articles, and stories the best they can be.",
            emoji: "\u270F\uFE0F",
            salaryRange: { entry: 40000, experienced: 100000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "creative-gaming",
        name: "Gaming & Interactive Media",
        careers: [
          {
            id: "creative-game-designer",
            title: "Game Designer",
            hook: "Dream up the rules, levels, and mechanics that make video games fun and addicting to play.",
            emoji: "\u{1F579}\uFE0F",
            salaryRange: { entry: 50000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "creative-game-artist",
            title: "Game Artist / 3D Modeler",
            hook: "Build the characters, weapons, and 3D worlds that players explore inside their favorite games.",
            emoji: "\u{1F3AE}",
            salaryRange: { entry: 45000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "creative-esports",
            title: "Esports Professional / Manager",
            hook: "Compete in video game tournaments for prize money or manage the teams that do.",
            emoji: "\u{1F3C6}",
            salaryRange: { entry: 30000, experienced: 100000 },
            growth: "high",
            education: "No formal requirement",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 6. Business, Finance & Entrepreneurship
  // ══════════════════════════════════════════
  {
    id: "business",
    name: "Business, Finance & Entrepreneurship",
    emoji: "\u{1F4BC}",
    color: "#2ECC71",
    description: "Start companies, manage money, and help organizations grow and succeed.",
    pathways: [
      {
        id: "biz-finance",
        name: "Finance & Investing",
        careers: [
          {
            id: "biz-financial-analyst",
            title: "Financial Analyst",
            hook: "Study markets and numbers to advise companies on how to invest millions of dollars wisely.",
            emoji: "\u{1F4CA}",
            salaryRange: { entry: 55000, experienced: 140000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-accountant",
            title: "Accountant / CPA",
            hook: "Be the money detective who tracks every dollar and makes sure businesses play by the rules.",
            emoji: "\u{1F9EE}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-financial-planner",
            title: "Financial Planner / Advisor",
            hook: "Help families and individuals plan their money so they can reach their biggest dreams.",
            emoji: "\u{1F4B0}",
            salaryRange: { entry: 45000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "biz-management",
        name: "Management & Leadership",
        careers: [
          {
            id: "biz-management-consultant",
            title: "Management Consultant",
            hook: "Help struggling companies solve their biggest problems and become more successful.",
            emoji: "\u{1F4CB}",
            salaryRange: { entry: 60000, experienced: 150000 },
            growth: "high",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "biz-project-manager",
            title: "Project Manager",
            hook: "Lead teams and organize complex projects from start to finish, making sure everything goes right.",
            emoji: "\u{1F4C5}",
            salaryRange: { entry: 55000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-hr-manager",
            title: "Human Resources Manager",
            hook: "Find and hire great people, then create a workplace where everyone does their best work.",
            emoji: "\u{1F91D}",
            salaryRange: { entry: 60000, experienced: 140000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "biz-entrepreneurship",
        name: "Entrepreneurship & Startups",
        careers: [
          {
            id: "biz-entrepreneur",
            title: "Entrepreneur / Startup Founder",
            hook: "Turn your own ideas into a real company and be your own boss from day one.",
            emoji: "\u{1F680}",
            salaryRange: { entry: 0, experienced: 200000 },
            growth: "high",
            education: "No formal requirement",
          },
          {
            id: "biz-product-manager",
            title: "Product Manager",
            hook: "Decide what features an app or product should have and guide the team that builds it.",
            emoji: "\u{1F4A1}",
            salaryRange: { entry: 65000, experienced: 155000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "biz-ecommerce",
            title: "E-Commerce Specialist",
            hook: "Build and run online stores that sell products to customers all around the world.",
            emoji: "\u{1F6D2}",
            salaryRange: { entry: 40000, experienced: 95000 },
            growth: "high",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "biz-marketing",
        name: "Marketing & Sales",
        careers: [
          {
            id: "biz-marketing-manager",
            title: "Marketing Manager",
            hook: "Create the campaigns and strategies that make people excited about products and brands.",
            emoji: "\u{1F4E3}",
            salaryRange: { entry: 60000, experienced: 180000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-social-media-manager",
            title: "Social Media Manager",
            hook: "Run a brand's social media accounts and create posts that go viral.",
            emoji: "\u{1F4F1}",
            salaryRange: { entry: 38000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-market-researcher",
            title: "Market Research Analyst",
            hook: "Figure out what people really want to buy and why, using surveys, data, and human psychology.",
            emoji: "\u{1F50E}",
            salaryRange: { entry: 45000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "biz-real-estate",
            title: "Real Estate Agent",
            hook: "Help people find and buy their dream homes, from cozy apartments to massive mansions.",
            emoji: "\u{1F3E0}",
            salaryRange: { entry: 30000, experienced: 100000 },
            growth: "stable",
            education: "High school diploma + license",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 7. Skilled Trades & Construction
  // ══════════════════════════════════════════
  {
    id: "trades",
    name: "Skilled Trades & Construction",
    emoji: "\u{1F528}",
    color: "#E67E22",
    description: "Build, fix, and maintain the things everyone depends on using hands-on skills and expertise.",
    pathways: [
      {
        id: "trades-electrical",
        name: "Electrical & Energy",
        careers: [
          {
            id: "trades-electrician",
            title: "Electrician",
            hook: "Wire up buildings, fix power systems, and keep the electricity flowing safely for everyone.",
            emoji: "\u26A1",
            salaryRange: { entry: 39000, experienced: 106000 },
            growth: "high",
            education: "Apprenticeship",
          },
          {
            id: "trades-solar-installer",
            title: "Solar Panel Installer",
            hook: "Climb onto rooftops and install the solar panels that turn sunlight into clean energy.",
            emoji: "\u2600\uFE0F",
            salaryRange: { entry: 35000, experienced: 70000 },
            growth: "high",
            education: "High school diploma + training",
          },
          {
            id: "trades-wind-tech",
            title: "Wind Turbine Technician",
            hook: "Climb hundreds of feet in the air to maintain the giant wind turbines that generate clean power.",
            emoji: "\u{1F4A8}",
            salaryRange: { entry: 45000, experienced: 85000 },
            growth: "high",
            education: "Postsecondary certificate",
          },
        ],
      },
      {
        id: "trades-construction",
        name: "Construction & Building",
        careers: [
          {
            id: "trades-carpenter",
            title: "Carpenter",
            hook: "Shape wood and other materials into the frames, walls, and details that make buildings real.",
            emoji: "\u{1FA9A}",
            salaryRange: { entry: 35000, experienced: 75000 },
            growth: "moderate",
            education: "Apprenticeship or on-the-job training",
          },
          {
            id: "trades-construction-manager",
            title: "Construction Manager",
            hook: "Lead entire building projects from blueprints to finished buildings, keeping everything on track.",
            emoji: "\u{1F3D7}\uFE0F",
            salaryRange: { entry: 60000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "trades-heavy-equipment",
            title: "Heavy Equipment Operator",
            hook: "Drive bulldozers, cranes, and excavators to move mountains of earth and build big projects.",
            emoji: "\u{1F69C}",
            salaryRange: { entry: 35000, experienced: 72000 },
            growth: "moderate",
            education: "High school diploma + training",
          },
        ],
      },
      {
        id: "trades-mechanical",
        name: "Plumbing, HVAC & Mechanical",
        careers: [
          {
            id: "trades-plumber",
            title: "Plumber",
            hook: "Install and fix the water and pipe systems that every home and building depends on.",
            emoji: "\u{1F527}",
            salaryRange: { entry: 38000, experienced: 100000 },
            growth: "stable",
            education: "Apprenticeship",
          },
          {
            id: "trades-hvac",
            title: "HVAC Technician",
            hook: "Install and repair heating and cooling systems so people stay comfortable year-round.",
            emoji: "\u2744\uFE0F",
            salaryRange: { entry: 38000, experienced: 85000 },
            growth: "high",
            education: "Postsecondary training",
          },
          {
            id: "trades-welder",
            title: "Welder",
            hook: "Use extreme heat to fuse metal together, building everything from bridges to race cars.",
            emoji: "\u{1F525}",
            salaryRange: { entry: 35000, experienced: 70000 },
            growth: "stable",
            education: "Postsecondary certificate",
          },
        ],
      },
      {
        id: "trades-automotive",
        name: "Automotive & Diesel",
        careers: [
          {
            id: "trades-auto-mechanic",
            title: "Automotive Technician",
            hook: "Diagnose and fix cars using high-tech tools \u2014 like being a doctor, but for vehicles.",
            emoji: "\u{1F697}",
            salaryRange: { entry: 32000, experienced: 72000 },
            growth: "stable",
            education: "Postsecondary certificate",
          },
          {
            id: "trades-diesel-tech",
            title: "Diesel Mechanic",
            hook: "Work on the powerful diesel engines inside big rigs, buses, and construction equipment.",
            emoji: "\u{1F69B}",
            salaryRange: { entry: 38000, experienced: 75000 },
            growth: "moderate",
            education: "Postsecondary certificate",
          },
          {
            id: "trades-ev-tech",
            title: "Electric Vehicle Technician",
            hook: "Service and repair the electric cars and batteries that are changing the future of transportation.",
            emoji: "\u{1F50B}",
            salaryRange: { entry: 40000, experienced: 80000 },
            growth: "high",
            education: "Postsecondary certificate",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 8. Law, Government & Public Service
  // ══════════════════════════════════════════
  {
    id: "law",
    name: "Law, Government & Public Service",
    emoji: "\u2696\uFE0F",
    color: "#34495E",
    description: "Uphold justice, shape laws, protect citizens, and serve your community and country.",
    pathways: [
      {
        id: "law-legal",
        name: "Legal Careers",
        careers: [
          {
            id: "law-lawyer",
            title: "Lawyer / Attorney",
            hook: "Argue cases in court, fight for justice, and help people navigate the legal system.",
            emoji: "\u2696\uFE0F",
            salaryRange: { entry: 65000, experienced: 200000 },
            growth: "moderate",
            education: "Doctoral degree (JD)",
          },
          {
            id: "law-judge",
            title: "Judge",
            hook: "Preside over courtroom trials and make the final call on cases that affect people's lives.",
            emoji: "\u{1F3DB}\uFE0F",
            salaryRange: { entry: 80000, experienced: 180000 },
            growth: "stable",
            education: "Doctoral degree (JD) + experience",
          },
          {
            id: "law-paralegal",
            title: "Paralegal",
            hook: "Research cases, organize evidence, and help lawyers prepare for their biggest courtroom battles.",
            emoji: "\u{1F4D1}",
            salaryRange: { entry: 38000, experienced: 85000 },
            growth: "stable",
            education: "Associate's or Bachelor's degree",
          },
        ],
      },
      {
        id: "law-enforcement",
        name: "Law Enforcement & Investigation",
        careers: [
          {
            id: "law-police-officer",
            title: "Police Officer",
            hook: "Protect your community, respond to emergencies, and keep people safe every day.",
            emoji: "\u{1F46E}",
            salaryRange: { entry: 42000, experienced: 100000 },
            growth: "stable",
            education: "High school diploma or Associate's",
          },
          {
            id: "law-detective",
            title: "Detective / Criminal Investigator",
            hook: "Solve crimes by gathering clues, interviewing witnesses, and piecing together the truth.",
            emoji: "\u{1F575}\uFE0F",
            salaryRange: { entry: 50000, experienced: 115000 },
            growth: "stable",
            education: "High school diploma + experience",
          },
          {
            id: "law-fbi-agent",
            title: "FBI / Federal Agent",
            hook: "Investigate the biggest, most dangerous cases in the country \u2014 from cyber-crime to terrorism.",
            emoji: "\u{1F50D}",
            salaryRange: { entry: 55000, experienced: 130000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "law-forensic-scientist",
            title: "Forensic Scientist",
            hook: "Analyze fingerprints, DNA, and crime scene evidence to help solve mysteries and catch criminals.",
            emoji: "\u{1F9EA}",
            salaryRange: { entry: 45000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "law-emergency",
        name: "Fire, Rescue & Emergency Services",
        careers: [
          {
            id: "law-firefighter",
            title: "Firefighter",
            hook: "Rush into burning buildings to save lives and protect your community from fires and disasters.",
            emoji: "\u{1F692}",
            salaryRange: { entry: 34000, experienced: 101000 },
            growth: "stable",
            education: "Postsecondary training",
          },
          {
            id: "law-dispatcher",
            title: "911 Dispatcher",
            hook: "Be the calm, quick-thinking voice on the phone that sends help when people need it most.",
            emoji: "\u{1F4DE}",
            salaryRange: { entry: 32000, experienced: 65000 },
            growth: "stable",
            education: "High school diploma",
          },
          {
            id: "law-emergency-manager",
            title: "Emergency Management Director",
            hook: "Plan and coordinate how entire cities respond to hurricanes, earthquakes, and other disasters.",
            emoji: "\u{1F198}",
            salaryRange: { entry: 50000, experienced: 115000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "law-government",
        name: "Government & Public Policy",
        careers: [
          {
            id: "law-diplomat",
            title: "Diplomat / Foreign Service Officer",
            hook: "Represent your country overseas and work to keep peace between nations around the world.",
            emoji: "\u{1F310}",
            salaryRange: { entry: 50000, experienced: 130000 },
            growth: "stable",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "law-urban-planner",
            title: "Urban Planner",
            hook: "Design the future layout of cities \u2014 where parks, roads, buildings, and neighborhoods should go.",
            emoji: "\u{1F5FA}\uFE0F",
            salaryRange: { entry: 50000, experienced: 100000 },
            growth: "moderate",
            education: "Master's degree",
          },
          {
            id: "law-policy-analyst",
            title: "Policy Analyst",
            hook: "Research big issues and write recommendations that help lawmakers make better decisions.",
            emoji: "\u{1F4DC}",
            salaryRange: { entry: 48000, experienced: 100000 },
            growth: "moderate",
            education: "Master's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 9. Education & Training
  // ══════════════════════════════════════════
  {
    id: "education",
    name: "Education & Training",
    emoji: "\u{1F4DA}",
    color: "#1ABC9C",
    description: "Inspire and teach the next generation, helping people learn and grow at every age.",
    pathways: [
      {
        id: "edu-teaching",
        name: "K-12 Teaching",
        careers: [
          {
            id: "edu-elementary-teacher",
            title: "Elementary School Teacher",
            hook: "Be the teacher who sparks a love of learning in young kids and helps them discover their talents.",
            emoji: "\u{1F4D6}",
            salaryRange: { entry: 42000, experienced: 82000 },
            growth: "stable",
            education: "Bachelor's degree + license",
          },
          {
            id: "edu-middle-teacher",
            title: "Middle / High School Teacher",
            hook: "Teach your favorite subject and be the mentor who helps teens figure out who they want to be.",
            emoji: "\u{1F3EB}",
            salaryRange: { entry: 43000, experienced: 85000 },
            growth: "stable",
            education: "Bachelor's degree + license",
          },
          {
            id: "edu-special-ed",
            title: "Special Education Teacher",
            hook: "Create personalized learning plans for students with unique needs so every kid gets a chance to shine.",
            emoji: "\u{1F31F}",
            salaryRange: { entry: 43000, experienced: 85000 },
            growth: "stable",
            education: "Bachelor's degree + license",
          },
          {
            id: "edu-pe-teacher",
            title: "Physical Education Teacher / Coach",
            hook: "Get kids moving, teach teamwork through sports, and help students build healthy habits for life.",
            emoji: "\u{1F3C0}",
            salaryRange: { entry: 40000, experienced: 80000 },
            growth: "stable",
            education: "Bachelor's degree + license",
          },
        ],
      },
      {
        id: "edu-higher",
        name: "Higher Education & Research",
        careers: [
          {
            id: "edu-professor",
            title: "College Professor",
            hook: "Teach college students, conduct groundbreaking research, and become an expert in your favorite subject.",
            emoji: "\u{1F393}",
            salaryRange: { entry: 50000, experienced: 130000 },
            growth: "moderate",
            education: "Doctoral degree",
          },
          {
            id: "edu-academic-advisor",
            title: "Academic Advisor",
            hook: "Guide students through college by helping them choose the right classes and career paths.",
            emoji: "\u{1F9ED}",
            salaryRange: { entry: 38000, experienced: 68000 },
            growth: "moderate",
            education: "Master's degree",
          },
        ],
      },
      {
        id: "edu-support",
        name: "Counseling & Student Support",
        careers: [
          {
            id: "edu-school-counselor",
            title: "School Counselor",
            hook: "Help students deal with tough times, plan for the future, and believe in themselves.",
            emoji: "\u{1F4AC}",
            salaryRange: { entry: 42000, experienced: 80000 },
            growth: "moderate",
            education: "Master's degree",
          },
          {
            id: "edu-school-psychologist",
            title: "School Psychologist",
            hook: "Use psychology to understand how kids learn and help remove barriers to their success.",
            emoji: "\u{1F9E0}",
            salaryRange: { entry: 55000, experienced: 110000 },
            growth: "moderate",
            education: "Specialist or Doctoral degree",
          },
          {
            id: "edu-librarian",
            title: "Librarian / Media Specialist",
            hook: "Curate amazing collections of books and digital resources and help people find exactly what they need.",
            emoji: "\u{1F4DA}",
            salaryRange: { entry: 42000, experienced: 80000 },
            growth: "stable",
            education: "Master's degree",
          },
        ],
      },
      {
        id: "edu-training",
        name: "Corporate Training & Instructional Design",
        careers: [
          {
            id: "edu-instructional-designer",
            title: "Instructional Designer",
            hook: "Create the online courses, training programs, and learning apps that teach people new skills.",
            emoji: "\u{1F5A5}\uFE0F",
            salaryRange: { entry: 50000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "edu-corporate-trainer",
            title: "Corporate Trainer",
            hook: "Teach employees at big companies new skills that help them do their jobs better.",
            emoji: "\u{1F3A4}",
            salaryRange: { entry: 45000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 10. Human Services & Community
  // ══════════════════════════════════════════
  {
    id: "health-human",
    name: "Human Services & Community",
    emoji: "\u{1F91D}",
    color: "#8E44AD",
    description: "Support people through life's challenges and help communities thrive.",
    pathways: [
      {
        id: "human-social",
        name: "Social Work & Counseling",
        careers: [
          {
            id: "human-social-worker",
            title: "Social Worker",
            hook: "Stand up for vulnerable people and connect families with the resources they need to thrive.",
            emoji: "\u{1F91D}",
            salaryRange: { entry: 40000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "human-mental-health-counselor",
            title: "Mental Health Counselor",
            hook: "Help people work through anxiety, depression, and tough times so they can feel like themselves again.",
            emoji: "\u{1F49A}",
            salaryRange: { entry: 38000, experienced: 80000 },
            growth: "high",
            education: "Master's degree",
          },
          {
            id: "human-psychologist",
            title: "Psychologist",
            hook: "Understand why people think and act the way they do, and help them overcome personal struggles.",
            emoji: "\u{1F9E0}",
            salaryRange: { entry: 60000, experienced: 130000 },
            growth: "moderate",
            education: "Doctoral degree",
          },
        ],
      },
      {
        id: "human-community",
        name: "Community & Nonprofit",
        careers: [
          {
            id: "human-nonprofit-director",
            title: "Nonprofit Director",
            hook: "Run an organization dedicated to making the world better \u2014 from fighting hunger to saving animals.",
            emoji: "\u{1F331}",
            salaryRange: { entry: 40000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "human-community-organizer",
            title: "Community Health Worker",
            hook: "Go into neighborhoods to connect people with healthcare, food, and services they need.",
            emoji: "\u{1F3D8}\uFE0F",
            salaryRange: { entry: 32000, experienced: 55000 },
            growth: "high",
            education: "High school diploma or Associate's",
          },
          {
            id: "human-fundraiser",
            title: "Fundraiser / Grant Writer",
            hook: "Raise the money that makes it possible for charities and causes to change people's lives.",
            emoji: "\u{1F49D}",
            salaryRange: { entry: 40000, experienced: 90000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "human-religion",
        name: "Religious & Spiritual Services",
        careers: [
          {
            id: "human-clergy",
            title: "Clergy / Minister / Rabbi / Imam",
            hook: "Lead a faith community, offer guidance during life's biggest moments, and inspire people spiritually.",
            emoji: "\u{1F64F}",
            salaryRange: { entry: 30000, experienced: 70000 },
            growth: "stable",
            education: "Bachelor's or Master's degree",
          },
          {
            id: "human-chaplain",
            title: "Chaplain",
            hook: "Comfort and support people in hospitals, the military, or prisons during their hardest days.",
            emoji: "\u262E\uFE0F",
            salaryRange: { entry: 35000, experienced: 65000 },
            growth: "stable",
            education: "Master's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 11. Agriculture, Food & Natural Resources
  // ══════════════════════════════════════════
  {
    id: "agriculture",
    name: "Agriculture, Food & Natural Resources",
    emoji: "\u{1F33E}",
    color: "#27AE60",
    description: "Grow food, manage natural resources, and protect the environment for future generations.",
    pathways: [
      {
        id: "ag-farming",
        name: "Farming & Ranching",
        careers: [
          {
            id: "ag-farmer",
            title: "Farmer / Rancher",
            hook: "Grow the food that feeds your community using a mix of hard work, science, and technology.",
            emoji: "\u{1F33E}",
            salaryRange: { entry: 30000, experienced: 80000 },
            growth: "stable",
            education: "No formal requirement",
          },
          {
            id: "ag-precision-ag",
            title: "Precision Agriculture Technologist",
            hook: "Use drones, GPS, and data to help farms grow more food using less water and fewer chemicals.",
            emoji: "\u{1F6F0}\uFE0F",
            salaryRange: { entry: 40000, experienced: 80000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "ag-agricultural-engineer",
            title: "Agricultural Engineer",
            hook: "Design smarter farm equipment and irrigation systems that help feed the whole planet.",
            emoji: "\u{1F69C}",
            salaryRange: { entry: 55000, experienced: 105000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "ag-food-science",
        name: "Food Science & Safety",
        careers: [
          {
            id: "ag-food-scientist",
            title: "Food Scientist",
            hook: "Invent new foods and recipes in a lab, making sure everything is delicious AND safe to eat.",
            emoji: "\u{1F354}",
            salaryRange: { entry: 48000, experienced: 105000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "ag-food-inspector",
            title: "Food Safety Inspector",
            hook: "Inspect restaurants, farms, and factories to make sure the food people eat is clean and safe.",
            emoji: "\u{1F50D}",
            salaryRange: { entry: 38000, experienced: 70000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "ag-nutritionist",
            title: "Dietitian / Nutritionist",
            hook: "Help people eat better by creating meal plans that boost health, energy, and athletic performance.",
            emoji: "\u{1F957}",
            salaryRange: { entry: 45000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's degree + license",
          },
        ],
      },
      {
        id: "ag-environment",
        name: "Natural Resources & Conservation",
        careers: [
          {
            id: "ag-park-ranger",
            title: "Park Ranger",
            hook: "Protect national parks, lead nature hikes, and help visitors experience the great outdoors.",
            emoji: "\u{1F3DE}\uFE0F",
            salaryRange: { entry: 35000, experienced: 65000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "ag-conservation-scientist",
            title: "Conservation Scientist",
            hook: "Develop plans to protect forests, wetlands, and wildlife habitats from human damage.",
            emoji: "\u{1F332}",
            salaryRange: { entry: 45000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "ag-wildlife-manager",
            title: "Fish & Wildlife Manager",
            hook: "Manage animal populations and their habitats so that wildlife thrives for generations to come.",
            emoji: "\u{1F43B}",
            salaryRange: { entry: 42000, experienced: 80000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "ag-animal",
        name: "Animal Science & Veterinary",
        careers: [
          {
            id: "ag-veterinarian",
            title: "Veterinarian",
            hook: "Be a doctor for animals \u2014 from family pets to zoo tigers to farm horses.",
            emoji: "\u{1F43E}",
            salaryRange: { entry: 75000, experienced: 160000 },
            growth: "high",
            education: "Doctoral degree (DVM)",
          },
          {
            id: "ag-vet-tech",
            title: "Veterinary Technician",
            hook: "Assist veterinarians with surgeries, take X-rays, and give loving care to sick animals.",
            emoji: "\u{1F415}",
            salaryRange: { entry: 30000, experienced: 50000 },
            growth: "moderate",
            education: "Associate's degree",
          },
          {
            id: "ag-animal-scientist",
            title: "Animal Scientist",
            hook: "Study how to keep livestock healthy and improve animal breeding using cutting-edge science.",
            emoji: "\u{1F404}",
            salaryRange: { entry: 45000, experienced: 90000 },
            growth: "moderate",
            education: "Bachelor's or Master's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 12. Hospitality, Tourism & Culinary Arts
  // ══════════════════════════════════════════
  {
    id: "hospitality",
    name: "Hospitality, Tourism & Culinary Arts",
    emoji: "\u{1F37D}\uFE0F",
    color: "#D35400",
    description: "Create amazing experiences for people through food, travel, events, and entertainment.",
    pathways: [
      {
        id: "hosp-culinary",
        name: "Culinary Arts & Food Service",
        careers: [
          {
            id: "hosp-chef",
            title: "Chef / Head Cook",
            hook: "Create mouthwatering dishes that wow diners, from local bistros to five-star restaurants.",
            emoji: "\u{1F468}\u200D\u{1F373}",
            salaryRange: { entry: 35000, experienced: 90000 },
            growth: "moderate",
            education: "Culinary school or on-the-job training",
          },
          {
            id: "hosp-pastry-chef",
            title: "Pastry Chef / Baker",
            hook: "Bake incredible cakes, pastries, and desserts that look almost too beautiful to eat.",
            emoji: "\u{1F382}",
            salaryRange: { entry: 30000, experienced: 65000 },
            growth: "moderate",
            education: "Culinary school or on-the-job training",
          },
          {
            id: "hosp-restaurant-manager",
            title: "Restaurant Manager",
            hook: "Run a restaurant from behind the scenes \u2014 hiring staff, managing finances, and keeping diners happy.",
            emoji: "\u{1F37D}\uFE0F",
            salaryRange: { entry: 38000, experienced: 75000 },
            growth: "moderate",
            education: "High school diploma + experience",
          },
        ],
      },
      {
        id: "hosp-travel",
        name: "Travel & Tourism",
        careers: [
          {
            id: "hosp-hotel-manager",
            title: "Hotel / Resort Manager",
            hook: "Run a hotel or resort and make sure every guest has an incredible, memorable stay.",
            emoji: "\u{1F3E8}",
            salaryRange: { entry: 39000, experienced: 127000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "hosp-travel-agent",
            title: "Travel Agent / Advisor",
            hook: "Plan dream vacations to exotic destinations and help people explore the world.",
            emoji: "\u2708\uFE0F",
            salaryRange: { entry: 30000, experienced: 60000 },
            growth: "moderate",
            education: "High school diploma + training",
          },
          {
            id: "hosp-tour-guide",
            title: "Tour Guide",
            hook: "Lead groups through historic cities, national parks, and famous landmarks while sharing amazing stories.",
            emoji: "\u{1F5FD}",
            salaryRange: { entry: 25000, experienced: 50000 },
            growth: "moderate",
            education: "No formal requirement",
          },
        ],
      },
      {
        id: "hosp-events",
        name: "Events & Recreation",
        careers: [
          {
            id: "hosp-event-planner",
            title: "Event Planner",
            hook: "Organize weddings, concerts, and big events where every detail has to be absolutely perfect.",
            emoji: "\u{1F389}",
            salaryRange: { entry: 35000, experienced: 75000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "hosp-sports-manager",
            title: "Sports & Entertainment Manager",
            hook: "Manage athletes, plan sporting events, and work in the exciting world of professional sports.",
            emoji: "\u{1F3DF}\uFE0F",
            salaryRange: { entry: 40000, experienced: 100000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "hosp-fitness-trainer",
            title: "Personal Trainer / Fitness Coach",
            hook: "Help people get stronger and healthier by designing custom workout plans and motivating them.",
            emoji: "\u{1F4AA}",
            salaryRange: { entry: 30000, experienced: 70000 },
            growth: "moderate",
            education: "Certification",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 13. Communications, Media & Journalism
  // ══════════════════════════════════════════
  {
    id: "communications",
    name: "Communications, Media & Journalism",
    emoji: "\u{1F4E1}",
    color: "#2980B9",
    description: "Inform, persuade, and connect people through news, storytelling, and digital media.",
    pathways: [
      {
        id: "comm-journalism",
        name: "Journalism & News",
        careers: [
          {
            id: "comm-journalist",
            title: "Journalist / Reporter",
            hook: "Investigate stories, uncover the truth, and report the news that keeps people informed.",
            emoji: "\u{1F4F0}",
            salaryRange: { entry: 35000, experienced: 100000 },
            growth: "declining",
            education: "Bachelor's degree",
          },
          {
            id: "comm-broadcast-anchor",
            title: "TV News Anchor / Broadcaster",
            hook: "Deliver breaking news on live TV to millions of viewers watching from their homes.",
            emoji: "\u{1F4FA}",
            salaryRange: { entry: 35000, experienced: 120000 },
            growth: "declining",
            education: "Bachelor's degree",
          },
          {
            id: "comm-podcast-host",
            title: "Podcast Producer / Host",
            hook: "Create your own show and build an audience of loyal listeners who tune in every week.",
            emoji: "\u{1F399}\uFE0F",
            salaryRange: { entry: 30000, experienced: 90000 },
            growth: "high",
            education: "No formal requirement",
          },
        ],
      },
      {
        id: "comm-pr",
        name: "Public Relations & Communications",
        careers: [
          {
            id: "comm-pr-specialist",
            title: "Public Relations Specialist",
            hook: "Shape how the public sees a company or person by crafting their story and managing their reputation.",
            emoji: "\u{1F3AF}",
            salaryRange: { entry: 41000, experienced: 130000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "comm-speechwriter",
            title: "Speechwriter",
            hook: "Write the powerful speeches that presidents, CEOs, and leaders deliver to move audiences.",
            emoji: "\u{1F5E3}\uFE0F",
            salaryRange: { entry: 45000, experienced: 110000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "comm-technical-writer",
            title: "Technical Writer",
            hook: "Explain complicated technology in simple language that anyone can understand.",
            emoji: "\u{1F4DD}",
            salaryRange: { entry: 55000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "comm-digital",
        name: "Digital Media & Social Platforms",
        careers: [
          {
            id: "comm-digital-marketer",
            title: "Digital Marketing Specialist",
            hook: "Use websites, ads, and SEO to help businesses reach the right customers online.",
            emoji: "\u{1F4BB}",
            salaryRange: { entry: 40000, experienced: 95000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "comm-ux-writer",
            title: "UX Writer / Content Strategist",
            hook: "Write the tiny words on buttons, menus, and screens that guide millions of people through apps.",
            emoji: "\u270D\uFE0F",
            salaryRange: { entry: 55000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "comm-translator",
            title: "Translator / Interpreter",
            hook: "Bridge language gaps so people who speak different languages can understand each other.",
            emoji: "\u{1F30D}",
            salaryRange: { entry: 38000, experienced: 85000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════
  // 14. Manufacturing, Logistics & Transportation
  // ══════════════════════════════════════════
  {
    id: "manufacturing",
    name: "Manufacturing, Logistics & Transportation",
    emoji: "\u{1F3ED}",
    color: "#7F8C8D",
    description: "Make, move, and deliver the products people depend on every single day.",
    pathways: [
      {
        id: "mfg-production",
        name: "Advanced Manufacturing & Production",
        careers: [
          {
            id: "mfg-industrial-engineer",
            title: "Industrial Engineer",
            hook: "Figure out how to build things faster, cheaper, and better in factories and businesses.",
            emoji: "\u{1F3ED}",
            salaryRange: { entry: 60000, experienced: 120000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "mfg-cnc-machinist",
            title: "CNC Machinist",
            hook: "Program computer-controlled machines to cut metal and plastic into precision parts with laser accuracy.",
            emoji: "\u{1F529}",
            salaryRange: { entry: 35000, experienced: 70000 },
            growth: "stable",
            education: "Postsecondary certificate",
          },
          {
            id: "mfg-quality-engineer",
            title: "Quality Control Engineer",
            hook: "Test products and catch defects before they reach customers, from cars to smartphones.",
            emoji: "\u2705",
            salaryRange: { entry: 50000, experienced: 100000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
          {
            id: "mfg-3d-printing",
            title: "3D Printing / Additive Manufacturing Specialist",
            hook: "Use cutting-edge 3D printers to create everything from medical implants to rocket parts.",
            emoji: "\u{1F5A8}\uFE0F",
            salaryRange: { entry: 45000, experienced: 90000 },
            growth: "high",
            education: "Associate's or Bachelor's degree",
          },
        ],
      },
      {
        id: "mfg-logistics",
        name: "Logistics & Supply Chain",
        careers: [
          {
            id: "mfg-logistician",
            title: "Logistician / Supply Chain Manager",
            hook: "Coordinate how products get from factories to stores, making sure the right stuff arrives on time.",
            emoji: "\u{1F4E6}",
            salaryRange: { entry: 49000, experienced: 132000 },
            growth: "high",
            education: "Bachelor's degree",
          },
          {
            id: "mfg-warehouse-manager",
            title: "Warehouse / Distribution Manager",
            hook: "Run massive warehouses full of products and get online orders out the door lightning-fast.",
            emoji: "\u{1F3E2}",
            salaryRange: { entry: 50000, experienced: 110000 },
            growth: "moderate",
            education: "Bachelor's degree",
          },
          {
            id: "mfg-purchasing-agent",
            title: "Purchasing Agent / Buyer",
            hook: "Negotiate deals and buy the raw materials and parts that companies need to make their products.",
            emoji: "\u{1F91D}",
            salaryRange: { entry: 42000, experienced: 90000 },
            growth: "stable",
            education: "Bachelor's degree",
          },
        ],
      },
      {
        id: "mfg-transport",
        name: "Transportation & Distribution",
        careers: [
          {
            id: "mfg-pilot",
            title: "Commercial Airline Pilot",
            hook: "Fly massive jets carrying hundreds of passengers to destinations around the world.",
            emoji: "\u2708\uFE0F",
            salaryRange: { entry: 80000, experienced: 210000 },
            growth: "moderate",
            education: "Bachelor's degree + flight training",
          },
          {
            id: "mfg-air-traffic",
            title: "Air Traffic Controller",
            hook: "Guide airplanes safely through the sky, making split-second decisions that protect lives.",
            emoji: "\u{1F5FC}",
            salaryRange: { entry: 70000, experienced: 150000 },
            growth: "stable",
            education: "Bachelor's degree or FAA training",
          },
          {
            id: "mfg-ship-captain",
            title: "Ship Captain / Marine Officer",
            hook: "Navigate enormous cargo ships and vessels across the oceans carrying goods between countries.",
            emoji: "\u{1F6A2}",
            salaryRange: { entry: 50000, experienced: 120000 },
            growth: "stable",
            education: "Bachelor's degree (Maritime Academy)",
          },
          {
            id: "mfg-truck-driver",
            title: "Commercial Truck Driver",
            hook: "Drive big rigs across the country, delivering everything from groceries to building materials.",
            emoji: "\u{1F69B}",
            salaryRange: { entry: 38000, experienced: 72000 },
            growth: "stable",
            education: "CDL license",
          },
        ],
      },
    ],
  },
];
