import { Career } from "./types";

export const CAREERS: Career[] = [
  // Builder (Realistic) careers
  {
    id: "mechanical-engineer",
    title: "Mechanical Engineer",
    description: "Design and build machines, robots, and mechanical systems that solve real-world problems.",
    icon: "\u{2699}\uFE0F",
    primaryCategory: "builder",
    secondaryCategory: "investigator",
  },
  {
    id: "architect",
    title: "Architect",
    description: "Design buildings and spaces where people live, work, and play.",
    icon: "\u{1F3D7}\uFE0F",
    primaryCategory: "builder",
    secondaryCategory: "creator",
  },
  {
    id: "electrician",
    title: "Electrician",
    description: "Install and maintain electrical systems that power homes, buildings, and cities.",
    icon: "\u{26A1}",
    primaryCategory: "builder",
    secondaryCategory: "organizer",
  },
  {
    id: "game-developer",
    title: "Video Game Developer",
    description: "Build the code and systems that make video games work — from physics to AI.",
    icon: "\u{1F3AE}",
    primaryCategory: "builder",
    secondaryCategory: "creator",
  },

  // Investigator (Investigative) careers
  {
    id: "marine-biologist",
    title: "Marine Biologist",
    description: "Study ocean life — from tiny plankton to massive whales — and protect marine ecosystems.",
    icon: "\u{1F42C}",
    primaryCategory: "investigator",
    secondaryCategory: "connector",
  },
  {
    id: "forensic-scientist",
    title: "Forensic Scientist",
    description: "Analyze evidence from crime scenes to help solve mysteries and bring justice.",
    icon: "\u{1F52C}",
    primaryCategory: "investigator",
    secondaryCategory: "organizer",
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    description: "Find hidden patterns in massive amounts of data to help companies and governments make better decisions.",
    icon: "\u{1F4CA}",
    primaryCategory: "investigator",
    secondaryCategory: "organizer",
  },
  {
    id: "astronomer",
    title: "Astronomer",
    description: "Study stars, planets, and galaxies to understand the mysteries of the universe.",
    icon: "\u{1F52D}",
    primaryCategory: "investigator",
    secondaryCategory: "creator",
  },

  // Creator (Artistic) careers
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    description: "Create visual designs for brands, websites, apps, and products that millions of people see.",
    icon: "\u{1F3A8}",
    primaryCategory: "creator",
    secondaryCategory: "builder",
  },
  {
    id: "film-director",
    title: "Film Director",
    description: "Lead the creative vision of movies and shows — from story to screen.",
    icon: "\u{1F3AC}",
    primaryCategory: "creator",
    secondaryCategory: "leader",
  },
  {
    id: "musician",
    title: "Music Producer",
    description: "Create, record, and produce music that people listen to around the world.",
    icon: "\u{1F3B5}",
    primaryCategory: "creator",
    secondaryCategory: "builder",
  },
  {
    id: "writer",
    title: "Author / Screenwriter",
    description: "Write stories, scripts, and narratives that entertain, inspire, and change perspectives.",
    icon: "\u{270F}\uFE0F",
    primaryCategory: "creator",
    secondaryCategory: "investigator",
  },

  // Connector (Social) careers
  {
    id: "teacher",
    title: "Teacher",
    description: "Help young people learn, grow, and discover what they're passionate about.",
    icon: "\u{1F4DA}",
    primaryCategory: "connector",
    secondaryCategory: "organizer",
  },
  {
    id: "doctor",
    title: "Doctor",
    description: "Diagnose and treat illnesses to keep people healthy and save lives.",
    icon: "\u{1FA7A}",
    primaryCategory: "connector",
    secondaryCategory: "investigator",
  },
  {
    id: "counselor",
    title: "School Counselor",
    description: "Support students through challenges and help them plan for their futures.",
    icon: "\u{1F91D}",
    primaryCategory: "connector",
    secondaryCategory: "leader",
  },
  {
    id: "social-worker",
    title: "Social Worker",
    description: "Help families and communities overcome difficulties and access the resources they need.",
    icon: "\u{1F49C}",
    primaryCategory: "connector",
    secondaryCategory: "organizer",
  },

  // Leader (Enterprising) careers
  {
    id: "entrepreneur",
    title: "Entrepreneur",
    description: "Start your own business, build a team, and turn an idea into something real.",
    icon: "\u{1F4A1}",
    primaryCategory: "leader",
    secondaryCategory: "builder",
  },
  {
    id: "lawyer",
    title: "Lawyer",
    description: "Argue cases, negotiate deals, and stand up for people's rights in the legal system.",
    icon: "\u{2696}\uFE0F",
    primaryCategory: "leader",
    secondaryCategory: "investigator",
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    description: "Create campaigns that get people excited about products, brands, and ideas.",
    icon: "\u{1F4E3}",
    primaryCategory: "leader",
    secondaryCategory: "creator",
  },
  {
    id: "politician",
    title: "Political Leader",
    description: "Shape laws and policies that affect millions of people's lives.",
    icon: "\u{1F3DB}\uFE0F",
    primaryCategory: "leader",
    secondaryCategory: "connector",
  },

  // Organizer (Conventional) careers
  {
    id: "project-manager",
    title: "Project Manager",
    description: "Keep complex projects on track — coordinate teams, timelines, and budgets.",
    icon: "\u{1F4CB}",
    primaryCategory: "organizer",
    secondaryCategory: "leader",
  },
  {
    id: "accountant",
    title: "Accountant",
    description: "Track and manage money for businesses and individuals — make sure every dollar is accounted for.",
    icon: "\u{1F4B0}",
    primaryCategory: "organizer",
    secondaryCategory: "investigator",
  },
  {
    id: "air-traffic-controller",
    title: "Air Traffic Controller",
    description: "Guide planes safely through the sky — precision and focus save lives every day.",
    icon: "\u{2708}\uFE0F",
    primaryCategory: "organizer",
    secondaryCategory: "builder",
  },
  {
    id: "event-planner",
    title: "Event Planner",
    description: "Organize amazing events — from concerts to conferences — making sure every detail is perfect.",
    icon: "\u{1F389}",
    primaryCategory: "organizer",
    secondaryCategory: "creator",
  },
];
