import { Career } from "./types";

export const CAREERS: Career[] = [
  // ── Health & Biomedical ──────────────────
  {
    id: "biomedical-engineering",
    title: "Biomedical Engineering",
    description: "Design medical devices, prosthetics, and technology that saves lives — where engineering meets medicine.",
    icon: "🫀",
    primaryCategory: "healthBiomedical",
    secondaryCategory: "designBuild",
  },
  {
    id: "genetics",
    title: "Genetics",
    description: "Decode DNA to understand inherited traits, fight genetic diseases, and unlock the secrets of life itself.",
    icon: "🧬",
    primaryCategory: "healthBiomedical",
    secondaryCategory: "lifeEcology",
  },
  {
    id: "biochemistry",
    title: "Biochemistry",
    description: "Study the chemical reactions inside living things — from how your cells produce energy to how drugs fight disease.",
    icon: "⚗️",
    primaryCategory: "healthBiomedical",
    secondaryCategory: "chemistryMaterials",
  },
  {
    id: "microbiology",
    title: "Microbiology",
    description: "Explore the invisible world of bacteria, viruses, and microbes that shape health, food, and the environment.",
    icon: "🦠",
    primaryCategory: "healthBiomedical",
    secondaryCategory: "lifeEcology",
  },

  // ── Life & Ecology ──────────────────────
  {
    id: "biology",
    title: "Biology",
    description: "Study life in all its forms — from cells to ecosystems — and understand how living things grow, adapt, and evolve.",
    icon: "🌿",
    primaryCategory: "lifeEcology",
    secondaryCategory: "healthBiomedical",
  },
  {
    id: "zoology",
    title: "Zoology",
    description: "Study animals in the wild and the lab — their behavior, evolution, and how to protect endangered species.",
    icon: "🐾",
    primaryCategory: "lifeEcology",
    secondaryCategory: "earthEnergy",
  },
  {
    id: "marine-sciences",
    title: "Marine Sciences",
    description: "Dive into ocean ecosystems — study marine life, coral reefs, and the vast underwater world.",
    icon: "🌊",
    primaryCategory: "lifeEcology",
    secondaryCategory: "earthEnergy",
  },
  {
    id: "environmental-science",
    title: "Environmental Science",
    description: "Tackle pollution, climate change, and conservation — protect the planet using science and data.",
    icon: "🌍",
    primaryCategory: "lifeEcology",
    secondaryCategory: "earthEnergy",
  },

  // ── Computing & Software ────────────────
  {
    id: "computer-science",
    title: "Computer Science",
    description: "Build software, apps, and algorithms that power everything from social media to self-driving cars.",
    icon: "💻",
    primaryCategory: "computing",
    secondaryCategory: "designBuild",
  },
  {
    id: "computer-engineering",
    title: "Computer Engineering",
    description: "Design the hardware and chips inside every device — where electrical engineering meets computer science.",
    icon: "🔌",
    primaryCategory: "computing",
    secondaryCategory: "designBuild",
  },
  {
    id: "data-science",
    title: "Data Science",
    description: "Turn massive datasets into insights that drive decisions in healthcare, business, and beyond.",
    icon: "📊",
    primaryCategory: "computing",
    secondaryCategory: "healthBiomedical",
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    description: "Defend networks, data, and systems from hackers and cyberattacks — be the guardian of the digital world.",
    icon: "🛡️",
    primaryCategory: "computing",
    secondaryCategory: "earthEnergy",
  },

  // ── Chemistry & Materials ───────────────
  {
    id: "chemistry",
    title: "Chemistry",
    description: "Understand and transform matter at the molecular level — create new medicines, materials, and reactions.",
    icon: "🧪",
    primaryCategory: "chemistryMaterials",
    secondaryCategory: "healthBiomedical",
  },
  {
    id: "chemical-engineering",
    title: "Chemical Engineering",
    description: "Scale up chemical reactions to manufacture fuels, plastics, food, and pharmaceuticals safely and efficiently.",
    icon: "🏭",
    primaryCategory: "chemistryMaterials",
    secondaryCategory: "designBuild",
  },
  {
    id: "materials-science",
    title: "Materials Science & Engineering",
    description: "Invent new materials — stronger metals, flexible electronics, self-healing polymers — that change what's possible.",
    icon: "🔬",
    primaryCategory: "chemistryMaterials",
    secondaryCategory: "designBuild",
  },
  {
    id: "physics",
    title: "Physics",
    description: "Discover the fundamental laws governing the universe — from subatomic particles to black holes.",
    icon: "⚛️",
    primaryCategory: "chemistryMaterials",
    secondaryCategory: "earthEnergy",
  },

  // ── Design & Build ──────────────────────
  {
    id: "mechanical-engineering",
    title: "Mechanical Engineering",
    description: "Design and build machines, robots, and systems — from tiny medical devices to massive jet engines.",
    icon: "⚙️",
    primaryCategory: "designBuild",
    secondaryCategory: "chemistryMaterials",
  },
  {
    id: "aerospace-engineering",
    title: "Aerospace Engineering",
    description: "Design aircraft, rockets, and spacecraft — push the boundaries of flight and space exploration.",
    icon: "🚀",
    primaryCategory: "designBuild",
    secondaryCategory: "earthEnergy",
  },
  {
    id: "civil-engineering",
    title: "Civil Engineering",
    description: "Design and build bridges, roads, skyscrapers, and water systems — the infrastructure that keeps civilization running.",
    icon: "🌉",
    primaryCategory: "designBuild",
    secondaryCategory: "earthEnergy",
  },
  {
    id: "industrial-engineering",
    title: "Industrial Engineering",
    description: "Optimize complex systems and processes — make factories, hospitals, and supply chains run smarter and faster.",
    icon: "📐",
    primaryCategory: "designBuild",
    secondaryCategory: "computing",
  },

  // ── Earth & Energy ──────────────────────
  {
    id: "geology",
    title: "Geology",
    description: "Study rocks, minerals, and Earth's structure — find natural resources and understand earthquakes and volcanoes.",
    icon: "🪨",
    primaryCategory: "earthEnergy",
    secondaryCategory: "chemistryMaterials",
  },
  {
    id: "meteorology",
    title: "Meteorology",
    description: "Forecast weather, track hurricanes, and study climate patterns using atmospheric science and computer models.",
    icon: "🌪️",
    primaryCategory: "earthEnergy",
    secondaryCategory: "computing",
  },
  {
    id: "environmental-engineering",
    title: "Environmental Engineering",
    description: "Engineer solutions for clean water, air pollution, and waste — build the systems that protect our planet.",
    icon: "♻️",
    primaryCategory: "earthEnergy",
    secondaryCategory: "designBuild",
  },
  {
    id: "nuclear-engineering",
    title: "Nuclear Engineering",
    description: "Harness the power of the atom — design reactors, develop clean energy, and advance medical imaging technology.",
    icon: "☢️",
    primaryCategory: "earthEnergy",
    secondaryCategory: "chemistryMaterials",
  },
];
